# Generated by Django 3.0.7 on 2020-07-21 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badminton', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='Draw_event_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DEkey', to='badminton.BWFTournament'),
        ),
    ]
