# Generated by Django 3.0.7 on 2020-07-21 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badminton', '0002_auto_20200721_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draw',
            name='trn_seas_id',
        ),
    ]
